apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-listner
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings: 
      - ref: cd-binding
      template:
        ref: cd-template
